# Generated by Django 2.1.2 on 2018-10-13 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tweet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='createdat',
            new_name='created_at',
        ),
    ]
